import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { ModeToggle } from '@/components/ui/themes/mode-toggle';
import { NavigationMenuHome } from '@/components/nav-menu/nav-home';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="fixed top-0 right-0 m-4 z-50">
                        <ModeToggle />
                    </div>
                    <div className="flex full-w justify-center mt-4 shadow-md">
                        <div className="mb-4">
                            <NavigationMenuHome className="" />
                        </div>
                    </div>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
